// Tarife, Add-ons und Preisverzeichnis von AKTEX.
// Alle Kosten werden vor jeder Order vollständig angezeigt (Kostentransparenz nach MiFID II).
export const PLANS = [
  {
    id: "free",
    name: "Free",
    monthly: 0,
    yearly: 0,
    fee: 1,
    ideaFee: 0.0025,
    creatorShare: 0.5,
    tagline: "Zum Reinschnuppern",
    limits: { indicators: 3, alerts: 3, aiDetails: false, copy: false, depth: 3 },
    features: ["Echtzeit-Charts & Watchlist", "1,00 € pro Order", "3 Indikatoren, 3 Alarme", "AKTEX AI – Gesamtbewertung", "Ideen-Börse: lesen, teilen, handeln"],
  },
  {
    id: "plus",
    name: "Plus",
    monthly: 4.99,
    yearly: 3.99,
    fee: 0.5,
    ideaFee: 0.002,
    creatorShare: 0.5,
    tagline: "Für Einsteiger",
    limits: { indicators: 5, alerts: 10, aiDetails: true, copy: false, depth: 5 },
    features: ["Alles aus Free", "0,50 € pro Order", "5 Indikatoren, 10 Alarme", "AKTEX AI mit Marken & Setups", "Orderbuch mit 5 Ebenen"],
  },
  {
    id: "pro",
    name: "Pro",
    monthly: 12.99,
    yearly: 9.99,
    fee: 0,
    ideaFee: 0.0015,
    creatorShare: 0.6,
    tagline: "Für aktive Trader",
    popular: true,
    limits: { indicators: 10, alerts: 50, aiDetails: true, copy: false, depth: 12 },
    features: ["Alles aus Plus", "0 € Ordergebühr", "10 Indikatoren, 50 Alarme", "Level-2-Orderbuch inklusive", "60 % Creator-Anteil an deinen Ideen"],
  },
  {
    id: "elite",
    name: "Elite",
    monthly: 29.99,
    yearly: 24.99,
    fee: 0,
    ideaFee: 0.001,
    creatorShare: 0.7,
    tagline: "Für Profis & Creator",
    limits: { indicators: 99, alerts: 999, aiDetails: true, copy: true, depth: 12 },
    features: ["Alles aus Pro", "Copy-Trading der Top-Trader", "Alle Add-ons inklusive", "70 % Creator-Anteil an deinen Ideen", "Unbegrenzte Indikatoren & Alarme"],
  },
  {
    id: "ai",
    name: "AKTEX AI",
    group: "ai",
    monthly: 99,
    yearly: 79,
    fee: 0,
    ideaFee: 0.001,
    creatorShare: 0.7,
    tagline: "Dein persönlicher KI-Berater",
    limits: { indicators: 99, alerts: 999, aiDetails: true, copy: true, depth: 12, ai: "assist" },
    features: ["Alles aus Elite", "KI-Berater-Chat rund um die Uhr", "Echtzeit-Meldungen zu Depot & Watchlist", "Depot-Doktor mit Score & Tipps", "Autopilot im Vorschlagsmodus – du bestätigst jeden Trade"],
  },
  {
    id: "aiprem",
    name: "AI Premium",
    group: "ai",
    monthly: 249,
    yearly: 199,
    fee: 0,
    ideaFee: 0.001,
    creatorShare: 0.7,
    tagline: "Der Autopilot für dein Depot",
    limits: { indicators: 99, alerts: 999, aiDetails: true, copy: true, depth: 12, ai: "auto" },
    features: ["Alles aus AKTEX AI", "Autopilot handelt selbstständig in deinen Limits", "3 Strategien, Trailing-Stops, Branchenlimits", "Protokoll mit Begründung für jede Entscheidung", "Not-Aus jederzeit · Prioritäts-Support"],
  },
];

export const ADDONS = [
  { id: "l2", name: "Level-2-Orderbuch", price: 4.99, icon: "📊", desc: "Volle Markttiefe mit 12 Ebenen für alle Aktien.", includedIn: ["pro", "elite", "ai", "aiprem"] },
  { id: "signals", name: "AI-Signal-Alarme", price: 6.99, icon: "⚡", desc: "Sofort-Meldung, sobald AKTEX AI das Rating einer Aktie ändert.", includedIn: ["elite", "ai", "aiprem"] },
  { id: "tax", name: "Steuer-Report", price: 2.99, icon: "🧾", desc: "Gewinne, Gebühren und geschätzte Abgeltungsteuer auf einen Blick.", includedIn: ["elite", "ai", "aiprem"] },
];

export const planById = (id) => PLANS.find((p) => p.id === id) || PLANS[0];
export const planPrice = (p, billing) => (billing === "yearly" ? p.yearly : p.monthly);
