// Arbeitstaschen – Vorlagen für neue Taschen: Abschnitte, typische Aufgaben und Meilensteine (Checklisten, keine Rechtsberatung)

// dueIn = Tage ab heute (nur bei den ersten Schritten), prio 0–3
export const TEMPLATES = [
  {
    id: "launch",
    name: "Produkt-Launch",
    emoji: "🚀",
    color: "blue",
    goal: "Das Produkt sauber an den Start bringen – mit Beta, Landingpage und Launch-Tag.",
    sections: ["Vorbereitung", "Produkt", "Marketing", "Launch"],
    tasks: [
      { title: "Zielgruppe und Versprechen in einem Satz festhalten", section: "Vorbereitung", prio: 2, dueIn: 1 },
      { title: "Launch-Datum festlegen", section: "Vorbereitung", prio: 3, dueIn: 2 },
      { title: "Beta-Tester einladen", section: "Produkt", prio: 2, dueIn: 5, subtasks: ["Liste mit 10 Testern", "Einladung schreiben", "Feedback-Formular"] },
      { title: "Kritische Fehler aus der Beta beheben", section: "Produkt", prio: 3 },
      { title: "Datenschutzerklärung und Impressum prüfen", section: "Produkt", prio: 2 },
      { title: "Landingpage mit Warteliste", section: "Marketing", prio: 2, subtasks: ["Headline + Nutzen", "Screenshots", "Anmeldeformular"] },
      { title: "Launch-Posts vorbereiten", section: "Marketing", prio: 1 },
      { title: "Presse- und Partnerliste", section: "Marketing", prio: 1 },
      { title: "Launch-Tag: Checkliste durchgehen", section: "Launch", prio: 3 },
      { title: "Ergebnisse nach einer Woche auswerten", section: "Launch", prio: 1 },
    ],
    milestones: [
      { title: "Beta startet", dueIn: 14 },
      { title: "Launch", dueIn: 42 },
    ],
  },
  {
    id: "company",
    name: "Firma / Gründung",
    emoji: "🏢",
    color: "indigo",
    goal: "Die Firma (UG/GmbH) sauber gründen – vom Namen bis zur Buchhaltung.",
    sections: ["Vorbereitung", "Notar & Bank", "Anmeldung", "Danach"],
    tasks: [
      { title: "Firmenname prüfen (Handelsregister, Marke, Domain)", section: "Vorbereitung", prio: 2, dueIn: 2 },
      { title: "Gesellschaftervertrag oder Musterprotokoll klären", section: "Vorbereitung", prio: 3, dueIn: 5 },
      { title: "Steuerberater auswählen", section: "Vorbereitung", prio: 2 },
      { title: "Notartermin vereinbaren", section: "Notar & Bank", prio: 3, dueIn: 7 },
      { title: "Geschäftskonto eröffnen", section: "Notar & Bank", prio: 2 },
      { title: "Stammkapital einzahlen", section: "Notar & Bank", prio: 2 },
      { title: "Handelsregistereintrag prüfen", section: "Anmeldung", prio: 2 },
      { title: "Gewerbe anmelden", section: "Anmeldung", prio: 2 },
      { title: "Fragebogen zur steuerlichen Erfassung (ELSTER)", section: "Anmeldung", prio: 2 },
      { title: "Transparenzregister prüfen", section: "Anmeldung", prio: 1 },
      { title: "Buchhaltung einrichten", section: "Danach", prio: 1 },
      { title: "Rechnungsvorlage erstellen", section: "Danach", prio: 1 },
      { title: "Versicherungen prüfen", section: "Danach", prio: 1 },
    ],
    milestones: [
      { title: "Notartermin", dueIn: 14 },
      { title: "Im Handelsregister", dueIn: 35 },
    ],
  },
  {
    id: "campaign",
    name: "Marketing-Kampagne",
    emoji: "📣",
    color: "pink",
    goal: "Eine Kampagne planen, produzieren, veröffentlichen und auswerten.",
    sections: ["Plan", "Produktion", "Veröffentlichen", "Auswerten"],
    tasks: [
      { title: "Ziel und Zielgruppe festlegen", section: "Plan", prio: 3, dueIn: 1 },
      { title: "Content-Plan für 4 Wochen", section: "Plan", prio: 2, dueIn: 3 },
      { title: "Posts und Clips produzieren", section: "Produktion", prio: 2, subtasks: ["Skripte", "Aufnahmen", "Schnitt", "Untertitel"] },
      { title: "Grafiken und Thumbnails", section: "Produktion", prio: 1 },
      { title: "Posting-Zeiten einplanen", section: "Veröffentlichen", prio: 1 },
      { title: "Kommentare und Nachrichten beantworten", section: "Veröffentlichen", prio: 1 },
      { title: "Kennzahlen prüfen", section: "Auswerten", prio: 1, repeat: "weekly" },
      { title: "Learnings festhalten", section: "Auswerten", prio: 1 },
    ],
    milestones: [{ title: "Kampagnenstart", dueIn: 10 }],
  },
  {
    id: "client",
    name: "Kundenprojekt",
    emoji: "🤝",
    color: "teal",
    goal: "Ein Kundenprojekt vom Angebot bis zur Rechnung im Griff haben.",
    sections: ["Angebot", "Umsetzung", "Abnahme"],
    tasks: [
      { title: "Anforderungen im Gespräch klären", section: "Angebot", prio: 3, dueIn: 1 },
      { title: "Angebot schreiben und senden", section: "Angebot", prio: 3, dueIn: 3 },
      { title: "Kick-off-Termin", section: "Umsetzung", prio: 2 },
      { title: "Zwischenstand präsentieren", section: "Umsetzung", prio: 2 },
      { title: "Feedback einarbeiten", section: "Umsetzung", prio: 2 },
      { title: "Abnahme einholen", section: "Abnahme", prio: 3 },
      { title: "Rechnung schreiben", section: "Abnahme", prio: 3 },
      { title: "Um Empfehlung oder Bewertung bitten", section: "Abnahme", prio: 1 },
    ],
    milestones: [
      { title: "Kick-off", dueIn: 7 },
      { title: "Abgabe", dueIn: 30 },
    ],
  },
  {
    id: "event",
    name: "Event",
    emoji: "🎉",
    color: "orange",
    goal: "Ein Event entspannt planen: Ort, Gäste, Ablauf und Nachbereitung.",
    sections: ["Planung", "Einladungen", "Tag X", "Danach"],
    tasks: [
      { title: "Datum, Budget und Gästezahl festlegen", section: "Planung", prio: 3, dueIn: 2 },
      { title: "Ort buchen", section: "Planung", prio: 3, dueIn: 7 },
      { title: "Catering klären", section: "Planung", prio: 2 },
      { title: "Einladungen verschicken", section: "Einladungen", prio: 2 },
      { title: "Zusagen nachhalten", section: "Einladungen", prio: 1 },
      { title: "Ablaufplan schreiben", section: "Tag X", prio: 2 },
      { title: "Technik und Material prüfen", section: "Tag X", prio: 2 },
      { title: "Fotos teilen und Danke sagen", section: "Danach", prio: 1 },
    ],
    milestones: [{ title: "Event", dueIn: 30 }],
  },
  {
    id: "learn",
    name: "Lernen",
    emoji: "📚",
    color: "green",
    goal: "Ein neues Thema Schritt für Schritt lernen und anwenden.",
    sections: ["Grundlagen", "Üben", "Anwenden"],
    tasks: [
      { title: "Lernziel in einem Satz aufschreiben", section: "Grundlagen", prio: 2, dueIn: 0 },
      { title: "Beste Quellen auswählen (Kurs, Buch, Videos)", section: "Grundlagen", prio: 2, dueIn: 2 },
      { title: "Lerneinheit", section: "Üben", prio: 1, repeat: "weekdays" },
      { title: "Notizen zusammenfassen", section: "Üben", prio: 1 },
      { title: "Kleines eigenes Projekt bauen", section: "Anwenden", prio: 2 },
    ],
    milestones: [{ title: "Erstes Projekt fertig", dueIn: 30 }],
  },
  {
    id: "empty",
    name: "Leer",
    emoji: "👜",
    color: "blue",
    goal: "",
    sections: [],
    tasks: [],
    milestones: [],
  },
];

export const template = (id) => TEMPLATES.find((t) => t.id === id) || null;
