// Arbeitstaschen – Vorlagen für neue Taschen: Abschnitte, typische Aufgaben und Meilensteine (Checklisten als Startpunkt)

// dueIn = Tage ab heute (nur bei den ersten Schritten), prio 0–3
export const TEMPLATES = [
  {
    id: "client",
    name: "Kunde / Auftrag",
    emoji: "🤝",
    color: "teal",
    goal: "Einen Auftrag vom ersten Gespräch bis zur Rechnung im Griff haben.",
    sections: ["Angebot", "Umsetzung", "Abrechnung"],
    tasks: [
      { title: "Anforderungen im Gespräch klären", section: "Angebot", prio: 3, dueIn: 1 },
      { title: "Angebot schreiben und senden", section: "Angebot", prio: 3, dueIn: 3 },
      { title: "Nachfassen, falls keine Antwort kommt", section: "Angebot", prio: 1, dueIn: 10 },
      { title: "Auftrag bestätigen und Termin festlegen", section: "Umsetzung", prio: 2 },
      { title: "Zwischenstand mit dem Kunden besprechen", section: "Umsetzung", prio: 2 },
      { title: "Abnahme einholen", section: "Abrechnung", prio: 3 },
      { title: "Rechnung schreiben", section: "Abrechnung", prio: 3 },
      { title: "Zahlungseingang prüfen", section: "Abrechnung", prio: 2 },
    ],
    milestones: [{ title: "Abgabe", dueIn: 30 }],
  },
  {
    id: "project",
    name: "Projekt",
    emoji: "📁",
    color: "blue",
    goal: "Ein Projekt planen, umsetzen und sauber abschließen.",
    sections: ["Planung", "Umsetzung", "Abschluss"],
    tasks: [
      { title: "Ziel und Umfang in zwei Sätzen festhalten", section: "Planung", prio: 3, dueIn: 1 },
      { title: "Beteiligte und Zuständigkeiten klären", section: "Planung", prio: 2, dueIn: 3 },
      { title: "Zeitplan mit Meilensteinen aufstellen", section: "Planung", prio: 2, dueIn: 5 },
      { title: "Budget und Kosten prüfen", section: "Planung", prio: 2 },
      { title: "Stand prüfen und nächste Schritte festlegen", section: "Umsetzung", prio: 2, repeat: "weekly" },
      { title: "Risiken und offene Fragen notieren", section: "Umsetzung", prio: 1 },
      { title: "Ergebnis übergeben", section: "Abschluss", prio: 3 },
      { title: "Was lief gut, was nicht? Kurz festhalten", section: "Abschluss", prio: 1 },
    ],
    milestones: [
      { title: "Planung fertig", dueIn: 7 },
      { title: "Projektende", dueIn: 60 },
    ],
  },
  {
    id: "office",
    name: "Büro & Verwaltung",
    emoji: "🗂️",
    color: "brown",
    goal: "Post, Belege, Rechnungen und Fristen ohne Stress im Blick.",
    sections: ["Regelmäßig", "Finanzen", "Fristen"],
    tasks: [
      { title: "Post und E-Mails durchsehen", section: "Regelmäßig", prio: 2, repeat: "weekdays" },
      { title: "Belege ablegen", section: "Regelmäßig", prio: 1, repeat: "weekly" },
      { title: "Offene Rechnungen prüfen und bezahlen", section: "Finanzen", prio: 2, repeat: "weekly" },
      { title: "Unterlagen für die Steuer sammeln", section: "Finanzen", prio: 1 },
      { title: "Verträge und Kündigungsfristen prüfen", section: "Fristen", prio: 2, repeat: "monthly" },
      { title: "Büromaterial nachbestellen", section: "Regelmäßig", prio: 0 },
    ],
    milestones: [],
  },
  {
    id: "team",
    name: "Team & Personal",
    emoji: "👥",
    color: "orange",
    goal: "Das Team gut organisieren: Besprechungen, Gespräche, Urlaub und Einarbeitung.",
    sections: ["Besprechungen", "Gespräche", "Planung"],
    tasks: [
      { title: "Teambesprechung vorbereiten", section: "Besprechungen", prio: 2, repeat: "weekly" },
      { title: "Mitarbeitergespräche planen", section: "Gespräche", prio: 2 },
      { title: "Feedback und Lob weitergeben", section: "Gespräche", prio: 1 },
      { title: "Urlaubsplanung abstimmen", section: "Planung", prio: 2 },
      { title: "Einarbeitung neuer Kollegen", section: "Planung", prio: 2, subtasks: ["Arbeitsplatz und Zugänge", "Ansprechpartner festlegen", "Plan für die ersten zwei Wochen"] },
      { title: "Aufgaben für die Woche verteilen", section: "Besprechungen", prio: 2 },
    ],
    milestones: [],
  },
  {
    id: "meeting",
    name: "Besprechung",
    emoji: "📅",
    color: "indigo",
    goal: "Eine Besprechung gut vorbereiten und danach nichts vergessen.",
    sections: ["Vorbereitung", "Nachbereitung"],
    tasks: [
      { title: "Agenda schreiben", section: "Vorbereitung", prio: 2, dueIn: 1 },
      { title: "Unterlagen an alle schicken", section: "Vorbereitung", prio: 2, dueIn: 2 },
      { title: "Protokoll schreiben", section: "Nachbereitung", prio: 2 },
      { title: "Aufgaben aus dem Termin verteilen", section: "Nachbereitung", prio: 3 },
      { title: "Offene Punkte nachfassen", section: "Nachbereitung", prio: 1 },
    ],
    milestones: [{ title: "Termin", dueIn: 7 }],
  },
  {
    id: "event",
    name: "Veranstaltung",
    emoji: "🎉",
    color: "pink",
    goal: "Eine Veranstaltung entspannt planen: Ort, Gäste, Ablauf und Nachbereitung.",
    sections: ["Planung", "Einladungen", "Tag X", "Danach"],
    tasks: [
      { title: "Datum, Budget und Gästezahl festlegen", section: "Planung", prio: 3, dueIn: 2 },
      { title: "Ort buchen", section: "Planung", prio: 3, dueIn: 7 },
      { title: "Essen und Getränke klären", section: "Planung", prio: 2 },
      { title: "Einladungen verschicken", section: "Einladungen", prio: 2 },
      { title: "Zusagen nachhalten", section: "Einladungen", prio: 1 },
      { title: "Ablaufplan schreiben", section: "Tag X", prio: 2 },
      { title: "Technik und Material prüfen", section: "Tag X", prio: 2 },
      { title: "Danke sagen und Fotos teilen", section: "Danach", prio: 1 },
    ],
    milestones: [{ title: "Veranstaltung", dueIn: 30 }],
  },
  {
    id: "learn",
    name: "Weiterbildung",
    emoji: "📚",
    color: "green",
    goal: "Ein neues Thema Schritt für Schritt lernen und im Job anwenden.",
    sections: ["Grundlagen", "Üben", "Anwenden"],
    tasks: [
      { title: "Lernziel in einem Satz aufschreiben", section: "Grundlagen", prio: 2, dueIn: 0 },
      { title: "Passenden Kurs oder passendes Buch auswählen", section: "Grundlagen", prio: 2, dueIn: 3 },
      { title: "Lerneinheit", section: "Üben", prio: 1, repeat: "weekly" },
      { title: "Das Gelernte im Alltag ausprobieren", section: "Anwenden", prio: 2 },
    ],
    milestones: [{ title: "Kurs abgeschlossen", dueIn: 60 }],
  },
  {
    id: "empty",
    name: "Leer",
    emoji: "👜",
    color: "blue",
    goal: "",
    sections: [],
    tasks: [],
    milestones: [],
  },
];

export const template = (id) => TEMPLATES.find((t) => t.id === id) || null;

// Bereiche für den ersten Start: Jeder wird zu einer LEEREN Tasche (nur Name, Symbol, Farbe, Abschnitte)
export const AREAS = [
  { id: "kunden", name: "Kunden", emoji: "🤝", color: "teal", sections: [] },
  { id: "projekte", name: "Projekte", emoji: "📁", color: "blue", sections: [] },
  { id: "buero", name: "Büro & Verwaltung", emoji: "🗂️", color: "brown", sections: ["Regelmäßig", "Finanzen", "Fristen"] },
  { id: "team", name: "Team", emoji: "👥", color: "orange", sections: [] },
  { id: "termine", name: "Termine & Besprechungen", emoji: "📅", color: "indigo", sections: [] },
  { id: "finanzen", name: "Finanzen & Rechnungen", emoji: "🧾", color: "green", sections: [] },
  { id: "weiterbildung", name: "Weiterbildung", emoji: "📚", color: "mint", sections: [] },
  { id: "privat", name: "Privates", emoji: "🏠", color: "pink", sections: [] },
];
